name = input( "What is your name: " )
age = int( input( "How old are you: " ) )
loc = input("location name: ")
year = str( ( 2021 - age ) + 100 )
print( name + " will be 100 years old in the year " + year )